# Generated by Django 2.1 on 2019-02-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idc', '0001_initial'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_number', models.SmallIntegerField(help_text='U位', verbose_name='U位')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idc.Cabinet', verbose_name='所处机房')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='server.Server', verbose_name='服务器')),
            ],
            options={
                'verbose_name': '机柜U位',
                'verbose_name_plural': '机柜U位',
                'ordering': ['id'],
            },
        ),
    ]
