# Generated by Django 2.1 on 2019-02-20 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetunit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetunit',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idc.Cabinet', verbose_name='所处机柜'),
        ),
    ]
