# Generated by Django 2.1 on 2019-03-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
        ('cabinetunit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinetunit',
            name='server',
        ),
        migrations.AddField(
            model_name='cabinetunit',
            name='server',
            field=models.ManyToManyField(blank=True, null=True, to='server.Server', verbose_name='服务器'),
        ),
    ]
