# Generated by Django 2.1 on 2019-03-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetunit', '0002_auto_20190311_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetunit',
            name='server',
            field=models.ManyToManyField(blank=True, to='server.Server', verbose_name='服务器'),
        ),
    ]
