# Generated by Django 2.1 on 2019-02-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetunit', '0002_auto_20190220_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetunit',
            name='u_number',
            field=models.CharField(help_text='U位', max_length=2, verbose_name='U位'),
        ),
    ]
