# Generated by Django 2.1 on 2019-03-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetunit', '0003_auto_20190311_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinetunit',
            name='server',
        ),
    ]
