# Generated by Django 2.1 on 2019-02-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufactory_name', models.CharField(db_index=True, help_text='厂商名称', max_length=64, unique=True, verbose_name='厂商名称')),
                ('tel_num', models.CharField(blank=True, help_text='支持电话', max_length=32, null=True, verbose_name='支持电话')),
                ('remark', models.TextField(blank=True, help_text='备注', max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '制造商',
                'verbose_name_plural': '制造商',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='型号名称', max_length=10, verbose_name='型号名称')),
                ('manufactory', models.ForeignKey(help_text='所属制造商', null=True, on_delete=django.db.models.deletion.CASCADE, to='manufactory.Manufactory', verbose_name='所属制造商')),
            ],
            options={
                'verbose_name': '产品型号',
                'verbose_name_plural': '产品型号',
                'ordering': ['id'],
            },
        ),
    ]
