# Generated by Django 2.1 on 2019-01-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactory',
            name='remark',
            field=models.TextField(help_text='备注', max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='manufactory',
            name='tel_num',
            field=models.CharField(help_text='支持电话', max_length=32, null=True, verbose_name='支持电话'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='manufactory',
            field=models.ForeignKey(help_text='所属制造商', null=True, on_delete=django.db.models.deletion.CASCADE, to='manufactory.Manufactory', verbose_name='所属制造商'),
        ),
    ]
