# Generated by Django 2.1 on 2019-02-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0002_auto_20190129_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufactory',
            options={'ordering': ['id'], 'verbose_name': '制造商', 'verbose_name_plural': '制造商'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['id'], 'verbose_name': '产品型号', 'verbose_name_plural': '产品型号'},
        ),
    ]
