# Generated by Django 2.1 on 2019-02-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0003_auto_20190214_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactory',
            name='remark',
            field=models.TextField(blank=True, help_text='备注', max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='manufactory',
            name='tel_num',
            field=models.CharField(blank=True, help_text='支持电话', max_length=32, null=True, verbose_name='支持电话'),
        ),
    ]
