# Generated by Django 2.1 on 2019-02-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('idc', '0001_initial'),
        ('manufactory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic_name', models.CharField(help_text='网卡名', max_length=16, verbose_name='网卡名')),
                ('mac_address', models.CharField(help_text='MAC地址', max_length=64, verbose_name='MAC地址')),
                ('remark', models.TextField(help_text='备注', max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '网卡',
                'verbose_name_plural': '网卡',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_managemant', models.GenericIPAddressField(db_index=True, help_text='管理IP', unique=True, verbose_name='管理IP')),
                ('hostname', models.CharField(db_index=True, help_text='主机名', max_length=24, verbose_name='主机名')),
                ('os_type', models.CharField(help_text='系统类型', max_length=16, verbose_name='系统类型')),
                ('os_release', models.CharField(help_text='操作系统版本', max_length=16, verbose_name='操作系统版本')),
                ('cpu_model', models.CharField(blank=True, help_text='CPU型号', max_length=128, null=True, verbose_name='CPU型号')),
                ('cpu_physics_count', models.SmallIntegerField(help_text='物理CPU个数', verbose_name='物理CPU个数')),
                ('cpu_core_count', models.SmallIntegerField(help_text='CPU核数', verbose_name='CPU核数')),
                ('cpu_logic_count', models.SmallIntegerField(help_text='逻辑CPU个数', verbose_name='逻辑CPU个数')),
                ('mem_capacity', models.DecimalField(decimal_places=2, help_text='内存大小(GB)', max_digits=10, verbose_name='内存大小(GB)')),
                ('disk_capacity', models.DecimalField(decimal_places=2, help_text='磁盘容量(GB)', max_digits=10, verbose_name='磁盘容量(GB)')),
                ('sn', models.CharField(db_index=True, help_text='序列号', max_length=128, unique=True, verbose_name='序列号')),
                ('uuid', models.CharField(blank=True, db_index=True, help_text='UUID', max_length=128, null=True, unique=True, verbose_name='UUID')),
                ('remark', models.TextField(help_text='备注', max_length=255, null=True, verbose_name='备注')),
                ('trade_date', models.DateField(help_text='购买日期', max_length=32, null=True, verbose_name='购买日期')),
                ('expire_date', models.DateField(help_text='过保日期', max_length=32, null=True, verbose_name='过保日期')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='创建时间', max_length=32, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', max_length=32, null=True, verbose_name='更新时间')),
                ('cabinet', models.ForeignKey(help_text='所属机柜', max_length=16, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='idc.Cabinet', verbose_name='所属机柜')),
                ('idc', models.ForeignKey(help_text='所属IDC机房', max_length=16, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='idc.Idc', verbose_name='所属IDC机房')),
                ('manufactory', models.ForeignKey(help_text='制造商', max_length=64, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manufactory.Manufactory', verbose_name='制造商')),
                ('productmodel', models.ForeignKey(help_text='设备型号', max_length=32, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manufactory.ProductModel', verbose_name='设备型号')),
                ('supplier', models.ForeignKey(help_text='供应商', max_length=12, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.Supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServerIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField(db_index=True, help_text='ip地址', unique=True, verbose_name='ip地址')),
                ('netmask', models.CharField(help_text='子网掩码', max_length=15, verbose_name='子网掩码')),
                ('remark', models.TextField(help_text='备注', max_length=255, null=True, verbose_name='备注')),
                ('nic', models.ForeignKey(help_text='所属网卡', on_delete=django.db.models.deletion.CASCADE, to='server.Nic', verbose_name='所属网卡')),
            ],
            options={
                'verbose_name': 'IP地址',
                'verbose_name_plural': 'IP地址',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='nic',
            name='server',
            field=models.ForeignKey(help_text='所属服务器', on_delete=django.db.models.deletion.CASCADE, to='server.Server', verbose_name='所属服务器'),
        ),
    ]
