# Generated by Django 2.1 on 2019-02-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='asset_name',
        ),
    ]
