# Generated by Django 2.1 on 2019-01-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'Cpu', 'verbose_name_plural': 'Cpu'},
        ),
        migrations.RemoveField(
            model_name='server',
            name='raid_type',
        ),
        migrations.AlterField(
            model_name='server',
            name='os_type',
            field=models.CharField(help_text='系统类型', max_length=16, verbose_name='系统类型'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(db_index=True, help_text='序列号', max_length=32, unique=True, verbose_name='序列号'),
        ),
    ]
