# Generated by Django 2.1 on 2019-03-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetunit', '0004_remove_cabinetunit_server'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cabinet_unit',
            field=models.ManyToManyField(blank=True, to='cabinetunit.CabinetUnit', verbose_name='机柜U位'),
        ),
    ]
