# Generated by Django 2.1 on 2019-04-11 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='供应商', max_length=12, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.Supplier', verbose_name='供应商'),
        ),
    ]
