# Generated by Django 2.1 on 2019-04-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190411_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='cabinet',
            field=models.ForeignKey(help_text='所属机柜', max_length=16, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idc.Cabinet', verbose_name='所属机柜'),
        ),
        migrations.AlterField(
            model_name='server',
            name='idc',
            field=models.ForeignKey(help_text='所属IDC机房', max_length=16, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idc.Idc', verbose_name='所属IDC机房'),
        ),
    ]
