# Generated by Django 2.1 on 2019-01-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190130_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='asset_name',
            field=models.CharField(db_index=True, help_text='资产编号', max_length=64, unique=True, verbose_name='资产编号'),
        ),
    ]
