# Generated by Django 2.1 on 2019-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190313_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='remark',
            field=models.TextField(blank=True, default='hahha', help_text='备注', max_length=255, verbose_name='备注'),
        ),
    ]
