# Generated by Django 2.1 on 2019-02-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190227_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nic',
            name='server',
            field=models.ForeignKey(help_text='所属服务器', on_delete=django.db.models.deletion.CASCADE, related_name='serverNic', to='server.Server', verbose_name='所属服务器'),
        ),
    ]
