# Generated by Django 2.1 on 2019-02-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190227_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nic',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='serverip',
            name='remark',
        ),
    ]
