# Generated by Django 2.1 on 2019-03-13 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190313_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='idc',
            field=models.ForeignKey(blank=True, default=1, help_text='所属IDC机房', max_length=16, on_delete=django.db.models.deletion.DO_NOTHING, to='idc.Idc', verbose_name='所属IDC机房'),
        ),
    ]
