# Generated by Django 2.1 on 2019-01-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190130_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='uuid',
            field=models.CharField(db_index=True, default='', help_text='UUID', max_length=64, unique=True, verbose_name='UUID'),
            preserve_default=False,
        ),
    ]
