# Generated by Django 2.1 on 2019-01-29 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_server_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='manufactory',
            field=models.ForeignKey(help_text='制造商', max_length=64, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manufactory.Manufactory', verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='server',
            name='productmodel',
            field=models.ForeignKey(help_text='设备型号', max_length=32, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manufactory.ProductModel', verbose_name='设备型号'),
        ),
    ]
