# Generated by Django 2.1 on 2019-01-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20190130_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(db_index=True, help_text='序列号', max_length=128, unique=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.CharField(db_index=True, help_text='UUID', max_length=128, unique=True, verbose_name='UUID'),
        ),
    ]
