# Generated by Django 2.1 on 2019-03-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20190313_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='cpu_core_count',
            field=models.SmallIntegerField(blank=True, help_text='CPU核数', null=True, verbose_name='CPU核数'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_logic_count',
            field=models.SmallIntegerField(blank=True, help_text='逻辑CPU个数', null=True, verbose_name='逻辑CPU个数'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_physics_count',
            field=models.SmallIntegerField(blank=True, help_text='物理CPU个数', null=True, verbose_name='物理CPU个数'),
        ),
        migrations.AlterField(
            model_name='server',
            name='disk_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='硬盘容量(GB)', max_digits=10, null=True, verbose_name='硬盘容量(GB)'),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(blank=True, db_index=True, help_text='主机名', max_length=24, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='server',
            name='mem_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='内存大小(GB)', max_digits=10, null=True, verbose_name='内存大小(GB)'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_type',
            field=models.CharField(blank=True, help_text='系统类型', max_length=16, null=True, verbose_name='系统类型'),
        ),
    ]
