# Generated by Django 2.1 on 2019-03-13 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20190313_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='idc',
            field=models.ForeignKey(blank=True, help_text='所属IDC机房', max_length=16, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='idc.Idc', verbose_name='所属IDC机房'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_release',
            field=models.CharField(blank=True, help_text='操作系统版本', max_length=16, null=True, verbose_name='操作系统版本'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(blank=True, db_index=True, help_text='序列号', max_length=128, null=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, help_text='UUID', max_length=128, null=True, verbose_name='UUID'),
        ),
    ]
