# Generated by Django 2.1 on 2019-03-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20190313_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='manufactory',
            field=models.ForeignKey(blank=True, help_text='制造商', max_length=64, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manufactory.Manufactory', verbose_name='制造商'),
        ),
    ]
