# Generated by Django 2.1 on 2019-03-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20190314_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='server',
            name='cabinet_unit',
        ),
        migrations.RemoveField(
            model_name='server',
            name='idc',
        ),
    ]
