# Generated by Django 2.1 on 2019-02-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20190212_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='cpu_core_count',
            field=models.SmallIntegerField(help_text='CPU核数', verbose_name='CPU核数'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_logic_count',
            field=models.SmallIntegerField(help_text='逻辑CPU个数', verbose_name='逻辑CPU个数'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_model',
            field=models.CharField(help_text='CPU型号', max_length=32, verbose_name='CPU型号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_physics_count',
            field=models.SmallIntegerField(help_text='物理CPU个数', verbose_name='物理CPU个数'),
        ),
    ]
