# Generated by Django 2.1 on 2019-03-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20190315_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='remark',
            field=models.TextField(blank=True, help_text='备注', max_length=255, verbose_name='备注'),
        ),
    ]
