# Generated by Django 2.1 on 2019-02-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20190212_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='cpu_model',
            field=models.CharField(help_text='CPU型号', max_length=128, verbose_name='CPU型号'),
        ),
    ]
