# Generated by Django 2.1 on 2019-02-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20190212_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='asset_type',
        ),
    ]
