# Generated by Django 2.1 on 2019-03-17 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0016_auto_20190317_1347'),
        ('server', '0011_auto_20190315_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cabinet',
            field=models.ForeignKey(help_text='所属机柜', max_length=16, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='idc.Cabinet', verbose_name='所属机柜'),
        ),
        migrations.AddField(
            model_name='server',
            name='idc',
            field=models.ForeignKey(help_text='所属IDC机房', max_length=16, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='idc.Idc', verbose_name='所属IDC机房'),
        ),
    ]
