# Generated by Django 2.1 on 2019-02-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_remove_server_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nic',
            name='mac_address',
            field=models.CharField(help_text='MAC地址', max_length=64, verbose_name='MAC地址'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='nic_name',
            field=models.CharField(help_text='网卡名', max_length=16, verbose_name='网卡名'),
        ),
    ]
