# Generated by Django 2.1 on 2019-03-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20190317_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='trade_date',
        ),
        migrations.AddField(
            model_name='server',
            name='approach_date',
            field=models.DateField(blank=True, help_text='进场日期', max_length=32, null=True, verbose_name='进场日期'),
        ),
    ]
