# Generated by Django 2.1 on 2019-04-04 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20190317_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='disk_capacity',
        ),
    ]
