# Generated by Django 2.1 on 2019-04-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='disk_name',
            new_name='driver_name',
        ),
    ]
