# Generated by Django 2.1 on 2019-04-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_auto_20190404_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='capacity',
            field=models.CharField(blank=True, help_text='硬盘大小', max_length=32, null=True, verbose_name='硬盘大小'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_name',
            field=models.CharField(help_text='设备名', max_length=32, verbose_name='设备名'),
        ),
    ]
