# Generated by Django 2.1 on 2019-04-04 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_auto_20190404_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='productmodel',
            field=models.ForeignKey(blank=True, help_text='设备型号', max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manufactory.ProductModel', verbose_name='设备型号'),
        ),
    ]
