# Generated by Django 2.1 on 2019-04-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_auto_20190404_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nic',
            name='ip_addr',
            field=models.GenericIPAddressField(db_index=True, help_text='ip地址', verbose_name='ip地址'),
        ),
    ]
