# Generated by Django 2.1 on 2019-03-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0011_auto_20190315_2203'),
        ('idc', '0015_auto_20190317_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(help_text='U位', verbose_name='U位')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='idc.Cabinet', verbose_name='所处机柜')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_server', to='server.Server', verbose_name='服务器')),
            ],
            options={
                'verbose_name': '机柜U位',
                'verbose_name_plural': '机柜U位',
                'ordering': ['id'],
            },
        ),
    ]
