# Generated by Django 2.1 on 2019-03-17 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uposition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uposition',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab_u', to='idc.Cabinet', verbose_name='所处机柜'),
        ),
    ]
