# Generated by Django 2.1 on 2019-02-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['id'], 'verbose_name': '供应商', 'verbose_name_plural': '供应商'},
        ),
    ]
