# Generated by Django 2.1 on 2019-02-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20190214_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='tel_num',
            field=models.CharField(blank=True, help_text='支持电话', max_length=16, null=True, verbose_name='支持电话'),
        ),
    ]
