# Generated by Django 2.1 on 2019-02-27 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20190227_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='tel_num',
            new_name='phone',
        ),
    ]
