# Generated by Django 2.1 on 2019-02-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permcontrol', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='用户名', max_length=32, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='电话', max_length=16, null=True, verbose_name='电话'),
        ),
    ]
