# Generated by Django 2.1 on 2019-03-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permcontrol', '0003_auto_20190301_0354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
