# Generated by Django 2.1 on 2019-03-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permcontrol', '0004_auto_20190301_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='电话', max_length=16, null=True, verbose_name='电话'),
        ),
    ]
