# Generated by Django 2.1 on 2019-01-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_name', models.CharField(max_length=10, verbose_name='机柜号')),
            ],
            options={
                'verbose_name': '机柜',
                'verbose_name_plural': '机柜',
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_name', models.CharField(max_length=32, unique=True, verbose_name='机房名称')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='机房地址')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='机房电话')),
                ('remark', models.TextField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'IDC机房',
                'verbose_name_plural': 'IDC机房',
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='idc.Idc', verbose_name='所处机房'),
        ),
    ]
