# Generated by Django 2.1 on 2019-04-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='idc_cab', to='idc.Idc', verbose_name='所处机房'),
        ),
    ]
