# Generated by Django 2.1 on 2019-03-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20190315_0827'),
        ('idc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='cabinetunit',
            name='cabinet',
        ),
        migrations.DeleteModel(
            name='Cabinet',
        ),
        migrations.DeleteModel(
            name='CabinetUnit',
        ),
        migrations.DeleteModel(
            name='Idc',
        ),
    ]
