# Generated by Django 2.1 on 2019-03-15 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idc', '0002_auto_20190315_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=32, unique=True, verbose_name='名称')),
                ('address', models.CharField(help_text='机房地址', max_length=128, null=True, verbose_name='机房地址')),
                ('phone', models.CharField(help_text='机房电话', max_length=16, null=True, verbose_name='机房电话')),
                ('remark', models.TextField(help_text='备注', max_length=255, null=True, verbose_name='备注')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='创建时间', max_length=32, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', max_length=32, null=True, verbose_name='更新时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父类级别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='idc.Idc', verbose_name='父类级别')),
            ],
            options={
                'verbose_name': 'IDC机房',
                'verbose_name_plural': 'IDC机房',
                'ordering': ['id'],
            },
        ),
    ]
