# Generated by Django 2.1 on 2019-01-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0003_auto_20190129_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='address',
            field=models.CharField(help_text='机房地址', max_length=128, null=True, verbose_name='机房地址'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='idc_name',
            field=models.CharField(help_text='机房名称', max_length=32, unique=True, verbose_name='机房名称'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='phone',
            field=models.CharField(help_text='机房电话', max_length=16, null=True, verbose_name='机房电话'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='remark',
            field=models.TextField(help_text='备注', max_length=255, null=True, verbose_name='备注'),
        ),
    ]
