# Generated by Django 2.1 on 2019-03-15 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0003_idc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idc',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='idc',
            name='parent_position',
            field=models.ForeignKey(blank=True, help_text='上级位置', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='idc.Idc', verbose_name='上级位置'),
        ),
    ]
