# Generated by Django 2.1 on 2019-03-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0004_auto_20190315_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idc',
            name='parent_position',
        ),
        migrations.DeleteModel(
            name='Idc',
        ),
    ]
