# Generated by Django 2.1 on 2019-01-29 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0005_auto_20190130_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idc.Idc', verbose_name='所处机房'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='address',
            field=models.CharField(max_length=128, null=True, verbose_name='机房地址'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='idc_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='机房名称'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='phone',
            field=models.CharField(max_length=16, null=True, verbose_name='机房电话'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='remark',
            field=models.TextField(max_length=255, null=True, verbose_name='备注'),
        ),
    ]
