# Generated by Django 2.1 on 2019-03-15 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0006_auto_20190315_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to='idc.Idc', verbose_name='所处机房'),
        ),
        migrations.AlterField(
            model_name='uposition',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uposition', to='idc.Cabinet', verbose_name='所处机柜'),
        ),
    ]
