# Generated by Django 2.1 on 2019-02-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0007_auto_20190130_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'ordering': ['id'], 'verbose_name': '机柜', 'verbose_name_plural': '机柜'},
        ),
        migrations.AlterModelOptions(
            name='idc',
            options={'ordering': ['id'], 'verbose_name': 'IDC机房', 'verbose_name_plural': 'IDC机房'},
        ),
    ]
