# Generated by Django 2.1 on 2019-03-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0007_auto_20190315_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', max_length=32, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='idc',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', max_length=32, null=True, verbose_name='更新时间'),
        ),
    ]
