# Generated by Django 2.1 on 2019-03-16 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0009_uposition_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uposition',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_server', to='server.Server', verbose_name='服务器'),
        ),
    ]
