# Generated by Django 2.1 on 2019-03-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0010_auto_20190316_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uposition',
            name='u_name',
            field=models.SmallIntegerField(help_text='U位', verbose_name='U位'),
        ),
    ]
