# Generated by Django 2.1 on 2019-03-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0012_auto_20190316_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabinet',
            old_name='cabinet_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='idc',
            old_name='idc_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='uposition',
            old_name='u_name',
            new_name='name',
        ),
    ]
