# Generated by Django 2.1 on 2019-03-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0013_auto_20190316_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='address',
            field=models.CharField(blank=True, help_text='机房地址', max_length=128, null=True, verbose_name='机房地址'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='phone',
            field=models.CharField(blank=True, help_text='机房电话', max_length=16, null=True, verbose_name='机房电话'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='remark',
            field=models.TextField(blank=True, help_text='备注', max_length=255, null=True, verbose_name='备注'),
        ),
    ]
