# Generated by Django 2.1 on 2019-03-17 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0014_auto_20190316_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uposition',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='uposition',
            name='server',
        ),
        migrations.DeleteModel(
            name='Uposition',
        ),
    ]
