# Generated by Django 2.1 on 2019-03-17 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0015_auto_20190317_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idc_cab', to='idc.Idc', verbose_name='所处机房'),
        ),
    ]
